name: GitHub Actions Demo
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    
    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: |
          ${{ secrets.DOCKER_USERNAME }}/mlops:latest
          ${{ secrets.DOCKER_USERNAME }}/mlops:${{ github.sha }}

    - name: Deploy to Production VM
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.VM_HOST }}
        username: ${{ secrets.VM_USER }}
        password: ${{ secrets.VM_PASSWORD }}
        script: |
          # Arrêter l'ancien container si il existe
          docker stop mlops-prod || true
          docker rm mlops-prod || true
          
          # Télécharger la nouvelle image
          docker pull ${{ secrets.DOCKER_USERNAME }}/mlops:latest
          
          # Nettoyer les anciennes images
          docker image prune -f
        
          # Lancer le nouveau container
          docker run -d -p 8963:8963 --name mlops-prod --restart unless-stopped ${{ secrets.DOCKER_USERNAME }}/mlops:latest